services:
  bantugrow:
    image: ghcr.io/agoesset/bantu-grow:latest
    container_name: bantugrow-app
    ports:
      - "3000:3000"
    volumes:
      - bantugrow-data:/data
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/data/bantugrow.db
    restart: always
    networks:
      - mutabaah-digital_default

volumes:
  bantugrow-data:

networks:
  mutabaah-digital_default:
    external: true
